server:
  port: 8501

spring:
  application:
    name: by-monitor-admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  security:
    user:
      name: byteyun
      password: 123456