server:
  port: 8201
spring:
  application:
    name: by-cloud-gateway
  autoconfigure: #close DataSourceAutoConfiguration
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:8501
        username: byteyun
        password: 123456
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://by-cloud:123456@localhost:8100/register/eureka/
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: by-cloud-auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: by-cloud-server-system
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: by-cloud-server-test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  SendErrorFilter: #config zuul exception
    error:
      disable: true
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ReadTimeout: 3000 # ReadTimeout: 3000