server:
  port: 8100
  servlet:
    context-path: /register
spring:
  application:
    name: by-register
  security: #\u914D\u7F6E\u9700\u8981\u8BBF\u95EE\u53D7\u4FDD\u62A4\u8D44\u6E90\u7684\u7528\u6237\u540D\u548C\u5BC6\u7801
    user:
      name: by-cloud
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #\u662F\u5426\u5C06eureka\u670D\u52A1\u6CE8\u518C\u5230\u670D\u52A1\u7AEF\uFF0C\u76EE\u524D\u5355\u670D\u52A1\uFF0C\u4E0D\u6CE8\u518C\u5230\u670D\u52A1\u7AEF\uFF0C\u6307\u5B9A\u4E3A false
    fetch-registry: false #\u4E0D\u9700\u8981\u4ECE\u522B\u7684\u670D\u52A1\u7AEF\u83B7\u53D6\u670D\u52A1\uFF0C\u6307\u5B9A\u4E3Afalse
    instance-info-replication-interval-seconds: 30 #\u6307\u5B9A30\u79D2\u540E\u624D\u80FD\u5C06\u670D\u52A1\u6CE8\u518C\u5230\u670D\u52A1\u7AEF
    service-url: #\u4E0B\u9762\u6307\u5B9Aeureka\u670D\u52A1\u7AEF\u5730\u5740
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
